# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

env:
  global:
    - RunAllRcppTests="yes"

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) the r-cran-rbenchmark package
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-runit r-cran-inline r-cran-rbenchmark r-cran-highlight r-cran-pkgkitten

script: 
  - ./run.sh run_tests

after_success:
  - ./run.sh coverage

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: kUzgzzpgBMc6a+qSjGovfU14U7x9GUXfghDgyF5qBaND/MjFpkmTBfW438Out2buiY+hFNnZc4zThifJM300cOXbcwVentmzuVQ5lLjBhTDvwQgdqytgWr/Ds9dErBeMXr178UD3MJXSOCLhO0wUke2xp2ZsDhsjquT+vFYnuk8=
      

