# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: release
            cntr: rcpp/ci
            r: R
          - name: r-4.0
            cntr: rcpp/ci-4.0
            r: R
          - name: r-3.6
            cntr: rcpp/ci-3.6
            r: R
          - name: r-3.5
            cntr: rcpp/ci-3.5
            r: R
          - name: dev
            cntr: rcpp/ci-dev
            r: RD

    steps:
      - uses: actions/checkout@v2

      #- name: Bootstrap
      #  run: |
      #    curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
      #    chmod 0755 run.sh
      #    ./run.sh bootstrap

      - name: Container
        run: docker pull ${{ matrix.cntr }}

      - name: SessionInfo
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${{ matrix.cntr }} ${{ matrix.r }} -q -e 'sessionInfo()'

      - name: Build
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${{ matrix.cntr }} ${{matrix.r }} CMD build --no-build-vignettes --no-manual .

      - name: Check
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt -e CI=true ${{ matrix.cntr }} ${{ matrix.r }} CMD check --no-vignettes --no-manual Rcpp_*.tar.gz

  covr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Container
        run: docker pull rcpp/ci

      - name: Coverage
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt -e CODECOV_TOKEN=${{secrets.CODECOV_TOKEN }} rcpp/ci r -l covr -e 'codecov()'
